name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, develop ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm run test -- --coverage
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: coverage

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - run: ./mvnw clean verify
      - uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: target/site/jacoco
